config/routes.rb
# config/routes.rb

Rails.application.routes.draw do

  scope module: "publicboard" do
    root to: "home#show"
    resource :home
    resource :about
    resources :stores
    resources :partners
  end

  namespace :adminboard do
    root to: "home#show"
    resource :home
    resources :legal_sections
    resources :administrators
    resources :sessions, only: [:new, :create, :destroy]
    resources :password_resets, except: [:show, :destroy, :index]
    get "login", to: "sessions#new", as: "login"
    get "logout", to: "sessions#destroy", as: "logout"
  end
end

app/models/administrator.rb
class Administrator < ActiveRecord::Base
  has_secure_password

  before_validation :generate_slug, on: :create, uniqueness: true
  before_validation :generate_auth_token, on: :create, uniqueness: true

  validates :email,    presence: true, uniqueness: :true, email: true

  def to_param
    slug
  end

  def send_reset_password
    generate_reset_password_token(:reset_password_token)
    self.reset_password_sent_at = Time.zone.now
    save!
    ResetPasswordMailer.reset_password(self).deliver_later
  end

  private

  include SlugGenerator
  include Adminboard::AuthTokenGenerator
  include Adminboard::ResetPasswordTokenGenerator
end

app/models/concerns/adminboard/auth_token_generator.rb
# model/concerns/adminboard/auth_token_generator.rb

module Adminboard::AuthTokenGenerator
  extend ActiveSupport::Concern

  # Auth Token Generator
  def generate_auth_token
    loop do
      self.authentication_token = Digest::SHA2.hexdigest("#{Time.now}").first(32)
      break unless Administrator.exists?(authentication_token: authentication_token)
    end
  end
end

app/models/concerns/adminboard/reset_password_token_generator.rb
# model/concerns/adminboard/reset_password_token_generator.rb

module Adminboard::ResetPasswordTokenGenerator
  extend ActiveSupport::Concern

  # Reset Password Token Generator
  def generate_reset_password_token(column)
    loop do
      self[column] = SecureRandom.urlsafe_base64
      break unless Administrator.exists?(reset_password_token: self[column])
    end
  end
end

app/controllers/adminboard/administrators_controller.rb
class Adminboard::AdministratorsController < AdminboardController
  before_action :set_administrator, only: [:show, :edit, :update, :destroy]

  def index
    @administrators = Administrator.all
  end

  def show
  end

  def new
    @administrator = Administrator.new
  end

  def edit
  end

  def create
    @administrator = Administrator.new(administrator_params)

    if @administrator.save
      flash[:success] = "Administrator was successfully created."
      redirect_to [:adminboard, @administrator]
    else
      flash.now[:failure] = "Oops. Something went wrong."
      render action: "new"
    end
  end

  def update
    if @administrator.update(administrator_params)
      flash[:success] = "Administrator was successfully created."
      redirect_to [:adminboard, @administrator]
    else
      flash.now[:failure] = "Oops. Something went wrong."
      render action: "edit"
    end
  end

  def destroy
    @administrator.destroy
    flash[:success] = "Administrator was successfully destroyed."
    redirect_to adminboard_login_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_administrator
      @administrator = current_administrator
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def administrator_params
      params.require(:administrator).permit(:email, :username, :password, :password_confirmation)
    end
end

app/controllers/adminboard/home_controller.rb
# adminboard/controllers/home_controller.rb

class Adminboard::HomeController < AdminboardController
  def show
  end
end

app/controllers/adminboard/legal_sections_controller.rb
class Adminboard::LegalSectionsController < AdminboardController
  before_action :set_legal_section, only: [:show, :edit, :update, :destroy]

  def index
    @legal_sections = LegalSection.all
  end

  def show
  end

  def new
    @legal_section = LegalSection.new
  end

  def edit
  end

  def create
    @legal_section = LegalSection.new(legal_section_params)

    if @legal_section.save
      flash[:success] = "Legal was successfully created."
      redirect_to [:adminboard, @legal_section]
    else
      flash.now[:failure] = "Oops. Something went wrong."
      render action: "new"
    end
  end

  def update
    if @legal_section.update(legal_section_params)
      flash[:success] = "Legal was successfully updated."
      redirect_to [:adminboard, @legal_section]
    else
      flash.now[:failure] = "Oops. Something went wrong."
      render action: "edit"
    end
  end

  def destroy
    @legal_section.destroy
    flash[:success] = "Legal was successfully destroyed."
    redirect_to adminboard_legal_sections_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_legal_section
      @legal_section = LegalSection.find_by_slug!(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def legal_section_params
      params.require(:legal_section).permit(:title, :active)
    end
end

app/controllers/adminboard/password_resets_controller.rb
# adminboard/controllers/password_resets_controller.rb

class Adminboard::PasswordResetsController < AdminboardController
  skip_before_action :authorize_administrator
  before_action :check_current_administrator, only: [:new, :edit]
  before_action :set_administrator, only: [:edit, :update]

  def new
  end

  def create
    if @administrator = Administrator.find_by_email(params[:email])
      @administrator.send_reset_password
      flash[:success] = "An email has been sent with further instructions in order to reset your password."
      redirect_to adminboard_login_path
    else
      flash[:failure] = "Oops. Something went wrong."
      redirect_to adminboard_login_path
    end
  end

  def edit
  end

  def update
    if @administrator.reset_password_sent_at < 2.hours.ago
      flash[:failure] = "Oops. Something went wrong."
      redirect_to adminboard_login_path
    elsif @administrator.update_attributes(administrator_params)
      flash[:success] = "Your password was successfully updated."
      redirect_to adminboard_login_path
    else
      flash[:failure] = "Oops. Something went wrong."
      redirect_to adminboard_login_path
    end
  end

  private

  def check_current_administrator
    redirect_to adminboard_root_path if current_administrator.present?
  end

  def set_administrator
    @administrator = Administrator.find_by_reset_password_token!(params[:id])
  end

  def administrator_params
    params.require(:administrator).permit(:password, :password_confirmation)
  end
end

app/controllers/adminboard/sessions_controller.rb
# adminboard/controllers/sessions_controller.rb

class Adminboard::SessionsController < AdminboardController
  skip_before_action :authorize_administrator

  def new
    # redirect_to adminboard_root_path if current_admin.present?
  end

  def create
    administrator = Administrator.find_by_email(params[:email])
    if administrator && administrator.authenticate(params[:password])
      session[:authentication_token] = administrator.authentication_token
      redirect_to adminboard_root_url
    else
      redirect_to adminboard_login_path
    end
  end

  def destroy
    session[:authentication_token] = nil
    redirect_to root_path if session.destroy
  end
end

app/controllers/adminboard_controller.rb
# controllers/adminboard_controller.rb

class AdminboardController < ApplicationController
  before_action :authorize_administrator
  layout :layout_to_render

  private

  # Defines the layout based on the administrator agent.
  def layout_to_render
    if browser.modern?
      "adminboard/application"
    else
      "adminboard/application"
    end
  end

  # Setup the current_administrator method.
  def current_administrator
    @current_administrator ||= Administrator.find_by_authentication_token!(session[:authentication_token]) if session[:authentication_token]
  end

  # Verifies if the Administrator is Logged in or not.
  def authorize_administrator
    redirect_to adminboard_login_path if current_administrator.nil?
  end

  # Creates the current_administrator.
  helper_method :current_administrator
end

app/views/adminboard/administrators/_form.html.haml
-# app/views/adminboard/administrators/_form.html.haml

= form_for([:adminboard, @administrator]) do |f|
  - if @administrator.errors.any?
    #error_explanation
      %h2 #{pluralize(@administrator.errors.count, "error")} prohibited this administrator from being saved:
      %ul
        - @administrator.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :email
    = f.text_field :email
  .field
    = f.label :password
    = f.password_field :password
  .field
    = f.label :password_confirmation
    = f.password_field :password_confirmation, autocomplete: :off
  .actions
    = f.submit "Save"

app/views/adminboard/administrators/edit.html.haml
-# app/views/adminboard/administrators/edit.html.haml

%h1 Editing administrator

= render "form"

= link_to "Show", [:adminboard, @administrator]

= link_to "Back", adminboard_administrators_path

app/views/adminboard/administrators/index.html.haml
-# app/views/adminboard/administrators/index.html.haml

%h1 Listing administrators

%table
  %tr
    %th Slug
    %th Email
    %th Password digest
    %th Authentication token
    %th Reset password token
    %th Reset password sent at
    %th Sudo
    %th
    %th
    %th

  - @administrators.each do |administrator|
    %tr
      %td= administrator.slug
      %td= administrator.email
      %td= administrator.password_digest
      %td= administrator.authentication_token
      %td= administrator.reset_password_token
      %td= administrator.reset_password_sent_at
      %td= administrator.sudo
      %td= link_to "Show", [:adminboard, administrator]
      %td= link_to "Edit", edit_adminboard_administrator_path(administrator)
      %td= link_to "Destroy", [:adminboard, administrator], :method => :delete, :data => { :confirm => "Are you sure?" }

%br

= link_to "New Administrator", new_adminboard_administrator_path

app/views/adminboard/administrators/new.html.haml
-# app/views/adminboard/administrators/new.html.haml

%h1 New administrator

= render "form"

= link_to "Back", adminboard_administrators_path

app/views/adminboard/administrators/show.html.haml
-# app/views/adminboard/administrators/show.html.haml

%p
  %b Slug:
  = @administrator.slug
%p
  %b Email:
  = @administrator.email
%p
  %b Password digest:
  = @administrator.password_digest
%p
  %b Authentication token:
  = @administrator.authentication_token
%p
  %b Reset password token:
  = @administrator.reset_password_token
%p
  %b Reset password sent at:
  = @administrator.reset_password_sent_at
%p
  %b Sudo:
  = @administrator.sudo

= link_to "Edit", edit_adminboard_administrator_path(@administrator)

= link_to "Back", adminboard_administrators_path