config/routes.rb
# config/routes.rb

Rails.application.routes.draw do

  scope module: "publicboard" do
    root to: "home#show"
    resource :home
    resource :about
    resources :stores
    resources :partners
  end

  namespace :adminboard do
    root to: "home#show"
    resource :home
    resources :legal_sections
    resources :administrators
    resources :sessions, only: [:new, :create, :destroy]
    resources :password_resets, except: [:show, :destroy, :index]
    get "login", to: "sessions#new", as: "login"
    get "logout", to: "sessions#destroy", as: "logout"
  end
end

app/controllers/adminboard/home_controller.rb
# adminboard/controllers/home_controller.rb

class Adminboard::HomeController < AdminboardController
  def show
  end
end

app/controllers/publicboard/about_controller.rb
# publicboard/controllers/about_controller.rb

class Publicboard::AboutController < PublicboardController
  def show
  end
end

app/controllers/publicboard/home_controller.rb
# publicboard/controllers/home_controller.rb

class Publicboard::HomeController < PublicboardController
  def show
  end
end

app/controllers/publicboard/partners_controller.rb
# publicboard/controllers/partners_controller.rb

class Publicboard::PartnersController < PublicboardController
  def index
  end
end

app/controllers/publicboard/stores_controller.rb
# publicboard/controllers/stores_controller.rb

class Publicboard::StoresController < PublicboardController
  def index
  end
end

app/controllers/publicboard_controller.rb
# controllers/public_controller.rb

class PublicboardController < ApplicationController
  layout :layout_to_render

  private

  # Defines the layout based on the administrator agent.
  def layout_to_render
    if browser.modern?
      "publicboard/application"
    else
      "publicboard/application"
    end
  end
end

app/views/publicboard/home/_billboard.html.haml
-# app/views/publicboard/home/_billboard.html.haml

.billboard
  .billboardBox
    .billboardItem
      .billboardLeftWrap
        %h1.billboardTitle Pede o teu recibo finalista.
        %p.billboardText Donec sed odio dui. Nullam quis risus eget urna mollis ornare vel eu leo. Praesent commodo cursus magna, vel scelerisque nisl consectetur et.
        %p.billboardText Praesent commodo cursus magna, vel scelerisque nisl consectetur et. Cras mattis consectetur purus sit amet fermentum. Nullam id dolor id nibh ultricies vehicula ut id elit.

app/views/publicboard/home/_header.html.haml
-# app/views/publicboard/home/_header.html.haml

%header.universal.purple20Bg
  .placeholder
    .wrap
      .row12Left
        -# start: Logo
        = render partial: "publicboard/partials/logo"
        -# end: Logo

        -# start: Main Menu
        = render partial: "publicboard/partials/mainMenu"
        -# end: Main Menu
    .clear

app/views/publicboard/home/_map.html.haml
-# app/views/publicboard/home/_map.html.haml

.map
  .mapBox
    .mapItem
      -# %iframe{allowfullscreen: "", frameborder: "0", height: "524", src: "https://www.google.com/maps/embed?pb=!1m10!1m8!1m3!1d25511.37311384616!2d-16.926175128202203!3d32.65716080849079!3m2!1i1024!2i768!4f13.1!5e0!3m2!1sen!2spt!4v1447266290301", style: "border:0", width: "100%"}

app/views/publicboard/home/_partners.html.haml
-# app/views/publicboard/home/_partners.html.haml

.partners
  .partnersBox
    .partnersItem
      %h2.partnersTitle Parceiros
      %p.partnersText Nullam id dolor id nibh ultricies vehicula ut id elit.
  %ul.partnersBox
    %li.partnersList
    %li.partnersList
    %li.partnersList
    %li.partnersList

app/views/publicboard/home/_podium.html.haml
-# app/views/publicboard/home/_podium.html.haml

.podium
  .podiumBox
    .podiumItem
      %h2.podiumTitle Escolas Aderentes
      %p.podiumText Nullam id dolor id nibh ultricies vehicula ut id elit.
  %ul.podiumBox
    %li.podiumList
      .podiumListSecond
        %h3.podiumName Mattis Risus Purus
    %li.podiumList
      .podiumListFirst
        %h3.podiumName Justo Cursus Tristique Tellus
    %li.podiumList
      .podiumListThird
        %h3.podiumName Magna Tellus

app/views/publicboard/home/_schools.html.haml
-# app/views/publicboard/home/_schools.html.haml

.grid
  %ul.gridBox
    %li.gridList
      %p.gridLabel Ullamcorper Vulputate
      %h3.gridName Sit Justo Vestibulum
    %li.gridList
      %p.gridLabel Fusce
      %h3.gridName Elit Justo Fermentum Commodo
    %li.gridList
      %p.gridLabel Mattis Ultricies
      %h3.gridName Ridiculus Tellus Ullamcorper
    %li.gridList
      %p.gridLabel Cras
      %h3.gridName Pharetra Pellentesque Mollis
    %li.gridList
      %p.gridLabel Ullamcorper Vulputate
      %h3.gridName Sit Justo Vestibulum
    %li.gridList
      %p.gridLabel Fusce
      %h3.gridName Elit Justo Fermentum Commodo
    %li.gridList
      %p.gridLabel Mattis Ultricies
      %h3.gridName Ridiculus Tellus Ullamcorper
    %li.gridList
      %p.gridLabel Cras
      %h3.gridName Pharetra Pellentesque Mollis

app/views/publicboard/home/_stores.html.haml
-# app/views/publicboard/home/_stores.html.haml

.stores
  .storesBox
    .storesItem
      %h2.storesTitle Lojas Aderentes
      %p.storesText Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum.
      = link_to "Ver Lista", stores_path, class: "storesLink"

app/views/publicboard/home/show.html.haml
-# app/views/publicboard/home/show.html.haml

-# start: Header
= render partial: "publicboard/home/header"
-# end: Header

.universal.purple20Bg
  .placeholder
    .wrap
      .row12Left
        -# start: Billboard
        = render partial: "billboard"
        -# end: Billboard
    .clear

.universal
  .placeholder
    .wrap
      .row12Left
        -# start: Stores
        = render partial: "stores"
        -# end: Stores
    .clear

.universal.purple20Bg
  .wrap
    .row00Left
      -# start: Map
      = render partial: "map"
      -# end: Map
  .clear

.universal
  .placeholder
    .wrap
      .row12Left
        -# start: Partners
        = render partial: "partners"
        -# end: Partners
    .clear

.universal
  .placeholder
    .wrap
      .row12Left
        -# start: Podium
        = render partial: "podium"
        -# end: Podium
    .clear

.universal
  .placeholder
    .wrap
      .row12Left
        -# start: Schools
        = render partial: "schools"
        -# end: Schools
    .clear